name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 8  # 修改名称以反映使用的 Java 版本
      uses: actions/setup-java@v4
      with:
        java-version: '8'  # 将 '11' 改为 '8'
        distribution: 'temurin'  # 或 'openjdk'（根据你的需求）
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
